### ISSUE TITLE
Allow saving for multiple file formats

### ISSUE THREAD

**Issue by kinoko87** [sayofthelor/flixel-screenshot-plugin#3]
OpenFL offers encoding for other image formats such as JPEG, may be good to implement support for selecting what format they should be saved as.

**Comment by dotevie** [comment]
i'll try to do it

**Comment by dotevie** [comment]
implemented, you can switch between them like this
```haxe
// somewhere after initialization
ScreenShotPlugin.saveFormat = JPEG;
// to switch back
ScreenShotPlugin.saveFormat = PNG;
```
